[package]
name = "lazer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "*"
ctr = "*"
hex = "*"
lazy_static = "1.5.0"
num-modular = "0.6.1"
pprof = { version = "0.15", features = ["flamegraph"] }
rand = "*"
rand_chacha = "*"
sha3 = "*"
